services:
  db:
    image: postgres:15
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:5432", "--", "sh", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
