# docker-compose.ci.yml
services:
  db:
    # no CI não publicar porta no host (usa rede interna do Compose)
    ports: []

  api:
    # desliga o env_file e injeta as variáveis vindas do Jenkins
    env_file: []
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_HOST: ${POSTGRES_SERVER}     # (caso seu app leia HOST em vez de SERVER)
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
