services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-bolamarcadadb}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "${POSTGRES_PORT:-5433}:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile       # opcional; o último estágio já é o runtime
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env                  # se você já usa .env local
    environment:
      POSTGRES_HOST: db       # garante host correto no container
      POSTGRES_SERVER: db
    ports:
      - "8000:8000"
    command: ["/wait-for-it.sh","db:5432","-t","30","--",
              "uvicorn","main:app","--host","0.0.0.0","--port","8000"]
