"""Initial Migration

Revision ID: d6d395f5fc39
Revises: fa8c9a0d8890
Create Date: 2025-09-29 23:06:39.638397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d395f5fc39'
down_revision: Union[str, Sequence[str], None] = 'fa8c9a0d8890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('sports_center_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('reviews_field_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'sports_centers', ['sports_center_id'], ['id'])
    op.drop_column('reviews', 'field_id')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('reviews', sa.Column('field_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_field_id_fkey'), 'reviews', 'fields', ['field_id'], ['id'])
    op.drop_column('reviews', 'sports_center_id')
    # ### end Alembic commands ###
