name: Upload Python Package

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  test:
    runs-on: ubuntu-latest
    needs:
      - release-build
      - pypi-publish

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt

      - name: Run tests
        run: pytest

  notification:
    runs-on: ubuntu-latest
    needs:
      - release-build
      - pypi-publish
      - test

    steps:
      - name: Install mailutils
        run: sudo apt-get install mailutils

      - name: Send email notification
        run: echo "Pipeline realizado com sucesso" | mail -s "Pipeline Notification" thomasvictor2909@gmail.com
