name: Upload Python Package

on:
  workflow_dispatch:
  push:
    branches: [main, master, FEAT-implementing-GitHubActions]
  pull_request:
    branches: [main, master, FEAT-implementing-GitHubActions]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs:
      - release-build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt

      - name: Run tests
        run: pytest

  notification:
    runs-on: ubuntu-latest
    needs:
      - release-build
      - test

    steps:
      - name: Install mailutils
        run: sudo apt-get install mailutils

      - name: Send email notification
        run: echo "Pipeline realizado com sucesso" | mail -s "Pipeline Notification" thomasvictor2909@gmail.com
